FROM debian:latest

# Install iptables
RUN apt-get update && apt-get install -y iptables && rm -rf /var/lib/apt/lists/*

# Copy firewall rules script
COPY rules.sh /firewall/rules.sh
RUN chmod +x /firewall/rules.sh

# Run firewall rules on container startup
CMD ["/bin/sh", "-c", "/firewall/rules.sh && sleep infinity"]