name: Setup Docker Networks
description: Creates external Docker networks with static subnets

runs:
  using: "composite"
  steps:
    - run: python3 -m pip install --quiet --user pyyaml ipaddress
      shell: bash

    - run: python3 .github/actions/setup-docker-networks/setup_external_networks.py
      shell: bash