name: Setup external Docker networks
description: "Creates external:true networks with unique, non-overlapping subnets"

inputs:
  compose-dir:
    description: "Folder containing docker-compose.yml"
    required: true

runs:
  using: composite
  steps:
    - shell: bash
      run: python3 -m pip install --quiet --user pyyaml ipaddress

    - name: Create external networks
      shell: bash
      run: |
        python "${{ github.action_path }}/setup_external_networks.py" \
          --compose-dir "${{ inputs.compose-dir }}"