name: Setup Docker Networks
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        python3 -m pip install --quiet --user pyyaml

    - shell: bash
      run: bash .github/actions/setup-docker-networks/get_subnets.sh

    - shell: bash
      run: python3 .github/actions/setup-docker-networks/setup_external_networks.py