version: '3.9'
services:
  openplc:
    build:
      context: ./openplc
      dockerfile: dockerfile
    stdin_open: true 
    tty: true
    privileged: true
    container_name: openplc
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - openplc_data:/home
    ports:
      - 8080:8080
      - 502:502
    networks:
      wnet:
        ipv4_address: 192.168.100.46
      fnet:
        ipv4_address: 192.168.101.33

  openplc_hmi:
    build:
      context: ./hmi
      dockerfile: dockerfile
    stdin_open: true
    tty: true
    privileged: true
    entrypoint: ["gunicorn", "app:app", "-b", "0.0.0.0:5000"]
    container_name: openplc_hmi
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - 5000:5000
    networks:
      wnet:
          ipv4_address: 192.168.100.47

  tcp_modbus:
    container_name: tcp_modbus_server
    build:
      context: ./tcp_modbus
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    privileged: true
    networks:
      wnet:
        ipv4_address: 192.168.100.48

networks:
  wnet:
    driver: bridge
    name: icsnet
    ipam:
      config:
        - subnet: 192.168.100.0/24
          gateway: 192.168.100.254
    driver_opts:
      com.docker.network.bridge.name: br_icsnet
  fnet:
    driver: bridge
    name: phynet
    ipam:
      config: 
      - subnet: 192.168.101.0/24
        gateway: 192.168.101.254
    driver_opts:
      com.docker.network.bridge.name: br_phynet

volumes:
  openplc_data: