services:
  kibana:
    image: docker.elastic.co/kibana/kibana:8.0.0
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    volumes:
      - ./elk-config/kibana:/usr/share/kibana/config
    networks:
      idmz_network:
        ipv4_address: 192.168.20.16

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.0.0
    container_name: elasticsearch
    cap_add:
      - NET_ADMIN
    environment:
      - discovery.type=single-node
      - "http.host=0.0.0.0"
      - "transport.host=127.0.0.1"
      - "xpack.security.enabled=false"
      - "xpack.security.enrollment.enabled=false"
      # - 'ES_JAVA_OPTS="-Xms512m -Xmx512m"'
    networks:
      idmz_network:
        ipv4_address: 192.168.20.6
    ports:
      - 9200:9200
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  logstash_idmz:
    image: docker.elastic.co/logstash/logstash:8.0.0
    container_name: logstash_idmz
    ports:
      - "5044:5044"
      - "9600:9600"
    volumes:
      - ./elk-config/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./elk-config/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
    networks:
      idmz_network:
        ipv4_address: 192.168.20.8

  logstash_site_operations:
    image: docker.elastic.co/logstash/logstash:8.0.0
    container_name: logstash_site_operations
    ports:
      - "5045:5044"
      - "9601:9600"
    volumes:
      - ./elk-config/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./elk-config/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
    networks:
      site_operations_network:
        ipv4_address: 192.168.39.7
  
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.0.0
    container_name: filebeat
    cap_add:
      - NET_ADMIN
    user: root
    depends_on:
      - logstash_idmz
      - logstash_site_operations
    volumes:
      - ./elk-config/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:rw  # Mount configuration file
      - ./logs:/logs:ro # Mount logs directory explicitly
      # Add volumes like: "- ./logs/nginx_logs:/logs/nginx"
      # - /var/lib/docker/containers:/var/lib/docker/containers:ro
      # - /var/run/docker.sock:/var/run/docker.sock
      # - ./tomcat_log:/var/log/scada:ro
    command: [ "sh", "-c", "chmod go-w /usr/share/filebeat/filebeat.yml && filebeat -e -strict.perms=false", "filebeat modules enable elasticsearch" ]
    networks:
      assembly_network:
        ipv4_address: 192.168.31.7
      utilities_network:
        ipv4_address: 192.168.32.5
      packaging_network:
        ipv4_address: 192.168.33.7

  telegraf_forwarder:
    image: telegraf:latest
    container_name: telegraf_forwarder
    cap_add:
      - NET_ADMIN
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:rw
    env_file:
      - ../industrial/historian.env
    networks:
      utilities_network:
        ipv4_address: 192.168.32.7

  grafana:
    container_name: grafana
    image: grafana/grafana-oss:latest
    cap_add:
      - NET_ADMIN
    networks:
      enterprise_network:
        ipv4_address: 192.168.10.15
    ports:
      - 3000:3000
    volumes:
      #   - ./grafana:/var/lib/grafana
      #   - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      #   - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      #   - ./grafana/dashboards:/var/lib/grafana/dashboards
      #   - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      # grafana:
      #   volumes:
      - grafana-storage:/var/lib/grafana:rw

networks:
  tempTIGtest:
  enterprise_network:
    external: true
  idmz_network:
    external: true
  assembly_network:
    external: true
  utilities_network:
    external: true
  packaging_network:
    external: true
  site_operations_network:
    external: true

volumes:
  elasticsearch_data:
  grafana-storage:
