services:
  kibana:
    image: docker.elastic.co/kibana/kibana:8.0.0
    container_name: kibana
    cap_add:
      - NET_ADMIN
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
      XPACK_SECURITY_ENCRYPTIONKEY: "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
      XPACK_REPORTING_ENCRYPTIONKEY: "cccccccccccccccccccccccccccccccc"
      XPACK_REPORTING_KIBANASERVER_HOSTNAME: "localhost"
    networks:
      idmz_network:
        ipv4_address: 192.168.20.16
    ports:
      - 5601:5601

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.0.0
    container_name: elasticsearch
    cap_add:
      - NET_ADMIN
    environment:
      - discovery.type=single-node
      - "http.host=0.0.0.0"
      - "transport.host=127.0.0.1"
      - "xpack.security.enabled=false"
      - "xpack.security.enrollment.enabled=false"
      # - 'ES_JAVA_OPTS="-Xms512m -Xmx512m"'
    networks:
      idmz_network:
        ipv4_address: 192.168.20.6
    ports:
      - 9200:9200
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  logstash_idmz:
    image: docker.elastic.co/logstash/logstash:8.0.0
    container_name: logstash_idmz
    cap_add:
      - NET_ADMIN
    depends_on:
      - elasticsearch
    networks:
      idmz_network:
        ipv4_address: 192.168.20.8
    ports:
      - 5003:5000
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro

  logstash_site_operations:
    image: docker.elastic.co/logstash/logstash:8.0.0
    container_name: logstash_site_operations
    cap_add:
      - NET_ADMIN
    depends_on:
      - elasticsearch
    networks:
      site_operations_network:
        ipv4_address: 192.168.39.7
    ports:
      - 5002:5000
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.0.0
    container_name: filebeat
    cap_add:
      - NET_ADMIN
    user: root
    depends_on:
      - logstash_idmz
      - logstash_site_operations
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:rw # Mount configuration file
      - ./logs:/logs:ro # Mount logs directory explicitly
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./tomcat_log:/var/log/scada:ro
    command: [ "sh", "-c", "chmod go-w /usr/share/filebeat/filebeat.yml && filebeat -e -strict.perms=false", "filebeat modules enable elasticsearch" ]
    networks:
      assembly_network:
        ipv4_address: 192.168.31.7
      utilities_network:
        ipv4_address: 192.168.32.5
      packaging_network:
        ipv4_address: 192.168.33.7

  telegraf_forwarder:
    image: telegraf:latest
    container_name: telegraf_forwarder
    cap_add:
      - NET_ADMIN
    # restart: unless-stopped
    # user: telegraf:999 #you need to find the GID of Docker if not added to Sudo group, found user ID by getent passwd
    volumes:
      - './telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro'
      # - '/:/hostfs:ro' # to monitor docker-vm
      # - '/var/run/docker.sock:/var/run/docker.sock' # to monitor docker containers
      # - '/home/ubuntu/docker/grafana-monitoring/telegraf/mibs:/usr/share/snmp/mibs' # mibs files [e.g., sophos]
    environment:
      - HOST_ETC=/hostfs/etc
      - HOST_PROC=/hostfs/proc
      - HOST_SYS=/hostfs/sys
      - HOST_VAR=/hostfs/var
      - HOST_RUN=/hostfs/run
      - HOST_MOUNT_PREFIX=/hostfs
    networks:
      utilities_network:
        ipv4_address: 192.168.32.7
    # entrypoint: ["/bin/sh", "-c", "sleep infinity"]

  grafana:
    container_name: grafana
    cap_add:
      - NET_ADMIN
    image: grafana/grafana-oss:main-ubuntu
    user: "0"
    networks:
      enterprise_network:
        ipv4_address: 192.168.10.15
    volumes:
      - ./grafana:/var/lib/grafana # This doesn't exist on the host need to fix
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.entrypoints=http"
      - "traefik.http.routers.grafana.rule=Host(`grafana.jimsgarage.co.uk`)"
      - "traefik.http.routers.grafana.middlewares=default-whitelist@file"
      - "traefik.http.middlewares.grafana-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.grafana.middlewares=grafana-https-redirect"
      - "traefik.http.routers.grafana-secure.entrypoints=https"
      - "traefik.http.routers.grafana-secure.rule=Host(`grafana.jimsgarage.co.uk`)"
      - "traefik.http.routers.grafana-secure.tls=true"
      - "traefik.http.routers.grafana-secure.service=grafana"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.docker.network=enterprise_network"

networks:
  enterprise_network:
    external: true
  idmz_network:
    external: true
  assembly_network:
    external: true
  utilities_network:
    external: true
  packaging_network:
    external: true
  site_operations_network:
    external: true

volumes:
  elasticsearch_data:
