services:
  kibana:
    image: docker.elastic.co/kibana/kibana:8.0.0
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      enterprise_network:
        ipv4_address: 192.168.10.6
    ports:
      - 5601:5601

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.0.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    networks:
      idmz_network:
        ipv4_address: 192.168.20.7

    ports:
      - 9200:9200
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  logstash_idmz:
    image: docker.elastic.co/logstash/logstash:8.0.0
    container_name: logstash_idmz
    depends_on:
      - elasticsearch
    networks:
      idmz_network:
        ipv4_address: 192.168.20.8
    ports:
      - 5001:5000
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro

  logstash_site_operations:
    image: docker.elastic.co/logstash/logstash:8.0.0
    container_name: logstash_site_operations
    depends_on:
      - elasticsearch
    networks:
      site_operations_network:
        ipv4_address: 192.168.39.6
    ports:
      - 5002:5000
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.0.0
    container_name: filebeat
    user: root
    depends_on:
      - logstash_idmz
      - logstash_site_operations
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:rw  # Mount configuration file
      - ./logs:/logs:ro                                     # Mount logs directory explicitly
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["sh", "-c", "chmod go-w /usr/share/filebeat/filebeat.yml && filebeat -e -strict.perms=false"]
    networks:
      assembly_network:
        ipv4_address: 192.168.31.7
      utilities_network:
        ipv4_address: 192.168.32.5
      packaging_network:
        ipv4_address: 192.168.33.6

networks:
  enterprise_network:
    external: true
  idmz_network:
    external: true
  assembly_network:
    external: true
  utilities_network:
    external: true
  packaging_network:
    external: true
  site_operations_network:
    external: true

volumes:
  elasticsearch_data:
