services:
  dummynetworkservice:
    image: alpine:latest
    networks:
        - enterprise_network
        - idmz_network
        - industrial_network



networks:
  enterprise_network:
    name: enterprise_network  # Explicitly setting name
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24
    driver_opts:
      com.docker.network.bridge.name: br_enterprise

  idmz_network:
    name: idmz_network
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.20.0/24
    driver_opts:
      com.docker.network.bridge.name: br_idmz

  industrial_network:
    name: industrial_network
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.30.0/24
    driver_opts:
      com.docker.network.bridge.name: br_industrial
