#!/bin/bash
# Querying Elastic Search
# Execute the script from a debugging container (like god_debug) that has access to /var/log and can reach Elasticsearch over the network.

echo "Simulating HTTP error..."
curl -I http://192.168.39.5/nonexistent-page

echo "Generating custom log entry..."
echo "TEST_LOG_ENTRY: $(date) - Generated by elastic_search.sh" >> /var/log/test.log

echo "Waiting for logs to be forwarded..."
sleep 15

echo "Querying Elasticsearch for test log entry..."
curl -X GET "http://192.168.20.7:9200/_search?pretty" -H 'Content-Type: application/json' -d'
{
  "query": {
    "match": {
      "message": "TEST_LOG_ENTRY"
    }
  }
}'
