FROM frrouting/frr:latest

ARG ROUTER_CONFIG

# RUN apt-get update && apt-get install -y iproute2 iputils-ping

COPY ${ROUTER_CONFIG} /etc/frr/frr.conf
COPY setup_routes.sh /setup_routes.sh

RUN chmod +x /setup_routes.sh

ENTRYPOINT ["/bin/sh", "-c", "/setup_routes.sh && /usr/lib/frr/docker-start"]