services:
  reverse-proxy:
    image: nginx
    stdin_open: true
    tty: true
    container_name: reverse-proxy
    volumes:
      - ./nginx/nginx.conf/:/etc/nginx/nginx.conf:ro
      - ../logging/logs/nginx:/var/log/nginx
    ports:
      - "443:443"
      - "80:80"
    networks:
      idmz_network:
        ipv4_address: 192.168.20.2
      enterprise_network:
        ipv4_address: 192.168.10.6
  
  historian-server:
    image: influxdb:latest
    container_name: historian-server
    environment:
      - INFLUXDB_DB=historian
      - INFLUXDB_USER=admin
      - INFLUXDB_PASSWORD=securepass
    volumes:
      - historian_data:/var/lib/influxdb
    networks:
      idmz_network:
        ipv4_address: 192.168.20.3

  remote-desktop-gateway:
    image: guacamole/guacamole
    container_name: remote-desktop-gateway
    depends_on:
      - guacd
      - postgres
    environment:
      - GUACD_HOSTNAME=guacd
      - POSTGRES_HOSTNAME=postgres
      - POSTGRES_DATABASE=guacdb
      - POSTGRES_USER=guacadmin
      - POSTGRES_PASSWORD=strongpassword
    ports:
      - "8443:8080"
    networks:
      idmz_network:
        ipv4_address: 192.168.20.4

  guacd:
    image: guacamole/guacd
    container_name: guacd
    restart: always
    networks:
      idmz_network:
        ipv4_address: 192.168.20.5

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_DB=guacdb
      - POSTGRES_USER=guacadmin
      - POSTGRES_PASSWORD=strongpassword
    networks:
      idmz_network:
        ipv4_address: 192.168.20.6

networks:
  idmz_network:
    external: true
  enterprise_network:
    external: true

volumes:
  historian_data:
