services:
  reverse-proxy:
    image: nginx
    stdin_open: true
    tty: true
    container_name: reverse-proxy
    cap_add:
      - NET_ADMIN
    volumes:
      - ./nginx/nginx.conf/:/etc/nginx/nginx.conf:ro
      - ../logging/logs/nginx:/var/log/nginx
    ports:
      - "443:443"
      - "80:80"
    networks:
      idmz_network:
        ipv4_address: 192.168.20.2
      enterprise_network:
        ipv4_address: 192.168.10.10

  remote-desktop-gateway:
    image: guacamole/guacamole
    container_name: remote-desktop-gateway
    cap_add:
      - NET_ADMIN
    depends_on:
      - guacd
      - postgres
    environment:
      - GUACD_HOSTNAME=guacd
      - POSTGRES_HOSTNAME=postgres
      - POSTGRES_DATABASE=guacdb
      - POSTGRES_USER=guacadmin
      - POSTGRES_PASSWORD=strongpassword
    ports:
      - "8443:8080"
    networks:
      idmz_network:
        ipv4_address: 192.168.20.3

  guacd:
    image: guacamole/guacd
    container_name: guacd
    cap_add:
      - NET_ADMIN
    networks:
      idmz_network:
        ipv4_address: 192.168.20.4

  postgres:
    image: postgres:latest
    container_name: postgres
    cap_add:
      - NET_ADMIN
    environment:
      - POSTGRES_DB=guacdb
      - POSTGRES_USER=guacadmin
      - POSTGRES_PASSWORD=strongpassword
    networks:
      idmz_network:
        ipv4_address: 192.168.20.5

  wireguard:
    image: linuxserver/wireguard:latest
    container_name: wireguard
    cap_add: [NET_ADMIN, SYS_MODULE]
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - SERVERURL=vpn.example.com
      - SERVERPORT=51820
      - PEERS=alice,bob
      - PEERDNS=1.1.1.1
      - INTERNAL_SUBNET=10.13.13.0
    volumes:
      - wireguard_config:/config          # <— shared
      - /lib/modules:/lib/modules:ro
    ports:
      - "51820:51820/udp"
    restart: unless-stopped
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
    networks:
      idmz_network:
        ipv4_address: 192.168.20.6

networks:
  idmz_network:
    external: true
  enterprise_network:
    external: true

volumes:
  historian_data:
  wireguard_config:
