services:

  # Assembly Enclave Services
  openplc:
    build:
      context: .
      dockerfile: industrial_component/openplc/Dockerfile
    stdin_open: true 
    tty: true
    container_name: openplc
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - openplc_data:/home
    ports:
      - "8080:8080"
      - "5020:502"
    networks:
      industrial_network:
        ipv4_address: 192.168.31.1

  openplc_hmi:
    build:
      context: ./industrial_component/hmi
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    entrypoint: ["gunicorn", "app:app", "-b", "0.0.0.0:5000"]
    container_name: openplc_hmi
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    # ports:
    #   - "5000:5000"
    networks:
      industrial_network:
        ipv4_address: 192.168.31.2

  tcp_modbus:
    container_name: tcp_modbus_server
    build:
      context: ./industrial_component/tcp_modbus
      dockerfile: Dockerfile
    depends_on:
      - openplc
    stdin_open: true
    tty: true
    ports:
      - "502:502"
    networks:
      industrial_network:
        ipv4_address: 192.168.31.3
    entrypoint: ["/bin/sh", "-c", "sleep infinity"]

  # zeek:
  #   image: zeek/zeek:latest
  #   container_name: zeek_ids
  #   cap_add:
  #     - NET_RAW
  #   network_mode: "host"
  #   build: 
  #    context: ./zeek/elastic
  #    dockerfile: Dockerfile
  #   networks:
  #     assembly_network:
  #       ipv4_address: 192.168.31.4
  #   # command: zeek -i af_packet::eth0 local
  #   entrypoint: ["zeek", "-i", "af_packet::ens160", "local" ]

  # Utilities Enclave Services
  scadalts:
    image: scadalts/scadalts:latest
    environment:
      - CATALINA_OPTS=-Xmx512m -Xms512m
    ports:
      - "8000:8080"
    depends_on:
      - database
    expose: ["8080"]
    networks:
      industrial_network:
        ipv4_address: 192.168.32.1

  database:
    container_name: mysql_database
    image: mysql/mysql-server:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=scadalts
    volumes:
      - scada_databases:/var/lib/mysql
    networks:
      industrial_network:
        ipv4_address: 192.168.32.2
    
  # bacnet_server:
  #   image: iotechsys/bacnet-server:latest
  #   container_name: bacnet_server
  #   networks:
  #     utilities_network:
  #       ipv4_address: 192.168.32.3

  rsyslog_server:
    image: rsyslog/syslog_appliance_alpine:latest
    container_name: rsyslog_server
    networks:
      utilities_network:
        ipv4_address: 192.168.32.4
    volumes:
      - ./logging/logs:/var/log

  # Packaging Enclave Services
  inventory_db:
    image: mysql/mysql-server:8.0
    container_name: inventory_db
    environment:
      MYSQL_ROOT_PASSWORD: inventory_pass
    networks:
      packaging_network:
        ipv4_address: 192.168.33.4

  inventory_client:
    image: ubuntu:latest
    container_name: inventory_client
    stdin_open: true
    tty: true
    depends_on:
      - inventory_db
    networks:
      packaging_network:
        ipv4_address: 192.168.33.5

  # Level 3 Site Operations Services
  ftp_server:
    image: delfer/alpine-ftp-server:latest
    container_name: file_server
    environment:
      USERS: "ftpuser|ftp_pass"
    networks:
      site_operations:
        ipv4_address: 192.168.39.1

networks:
  industrial_network:
    external: true
  assembly_network:
    external: true
  utilities_network:
    external: true
  packaging_network:
    external: true
  site_operations:
    external: true
  
volumes:
  openplc_data:
  scada_databases:
  logs:
