services:

  # Assembly Enclave Services
  openplc_hmi:
    build:
      context: ./industrial_component/hmi
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    entrypoint: ["gunicorn", "app:app", "-b", "0.0.0.0:5000"]
    container_name: openplc_hmi
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    # ports:
    #   - "5000:5000"
    networks:
      assembly_network:
        ipv4_address: 192.168.31.2

  tcp_modbus:
    container_name: tcp_modbus_server
    build:
      context: ./industrial_component/tcp_modbus
      dockerfile: Dockerfile
    # depends_on:
    #   - openplc
    stdin_open: true
    tty: true
    ports:
      - "502:502"
    networks:
      assembly_network:
        ipv4_address: 192.168.31.3
    entrypoint: ["/bin/sh", "-c", "sleep infinity"]

  openplc:
    build:
      context: .
      dockerfile: industrial_component/openplc/Dockerfile
    stdin_open: true 
    tty: true
    container_name: openplc
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - openplc_data:/home
    ports:
      - "8080:8080"
      - "503:502"
    networks:
      assembly_network:
        ipv4_address: 192.168.31.4

  mqtt_broker:
    image: eclipse-mosquitto
    container_name: mqtt_broker
    networks:
      assembly_network:
        ipv4_address: 192.168.31.5
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mqtt/config:/mosquitto/config # loads the mosquitto config file
      # - ./mqtt/data:/mosquitto/data # If you enable persistence true in mosquitto.conf, this is where message queues and subscriptions are stored across restarts.
      - ./mqtt/log:/mosquitto/log # can be used for logging MQTT connect/disconnect messages
    
  node_red:
    image: nodered/node-red
    container_name: node_red
    networks:
      assembly_network:
        ipv4_address: 192.168.31.6
    ports:
      - "1880:1880"
    volumes:
      - ./node-red/data:/data # Saves Node-RED flows, custom nodes, credentials and project settings to the project
    depends_on:
      - mqtt_broker

  # zeek:
  #   image: zeek/zeek:latest
  #   container_name: zeek_ids
  #   cap_add:
  #     - NET_RAW
  #   network_mode: "host"
  #   build: 
  #    context: ./zeek/elastic
  #    dockerfile: Dockerfile
  #   networks:
  #     assembly_network:
  #       ipv4_address: 192.168.31.4
  #   # command: zeek -i af_packet::eth0 local
  #   entrypoint: ["zeek", "-i", "af_packet::ens160", "local" ]

  # Utilities Enclave Services
  scadalts:
    image: scadalts/scadalts:latest
    environment:
      - CATALINA_OPTS=-Xmx2G -Xms2G
      - JAVA_OPTS=-Dlogback.configurationFile=/usr/local/tomcat/lib/logback.xml
    ports: 
      - "0.0.0.0:8000:8080"
    depends_on: 
      - database
    expose: ["8080", "8000"]
    volumes:
      - ./tomcat_log:/usr/local/tomcat/logs:rw
      - ./industrial/scada/logback.xml:/usr/local/tomcat/lib/logback.xml:ro
      - scada_databases:/var/lib/mysql
      - ./industrial/scada/base_scada.json:/usr/local/tomcat/conf/base_scada.json:ro
    links:
      - database:database
    command:
      - /usr/bin/wait-for-it
      - --host=database
      - --port=3306
      - --timeout=30
      - --strict
      - --
      - /usr/local/tomcat/bin/catalina.sh
      - run
    networks:
      utilities_network:
        ipv4_address: 192.168.32.2
    
  database:
    container_name: mysql_database
    image: mysql/mysql-server:8.0.32
    ports:
      - "0.0.0.0:3307:3306"
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=scadalts
    expose: ["3307"]
    volumes:
      - ./db_data:/var/lib/mysql:rw
      - ./db_conf:/etc/mysql:ro
    command: --log_bin_trust_function_creators=1
    networks:
      utilities_network:
        ipv4_address: 192.168.32.3
    
  # bacnet_server:
  #   image: iconics/bacnet:10.97rlp4
  #   container_name: bacnet_server
  #   networks:
  #     utilities_network:
  #       ipv4_address: 192.168.32.4
  #   ports:
  #     - "47808:47808"

  # rsyslog_server:
  #   image: rsyslog/syslog_appliance_alpine:latest
  #   container_name: rsyslog_server
  #   networks:
  #     utilities_network:
  #       ipv4_address: 192.168.32.5
  #   volumes:
  #     - ./logging/logs:/var/log

  opc_ua_server:
    image: open62541/open62541:latest
    container_name: opc_ua_server
    ports:
      - "4840:4840"  # OPC UA default port
    environment:
      - OPCUA_SERVER_NAME=Utilities_Server
      - OPCUA_NAMESPACE_URI=http://example.com/opcua
    networks:
      utilities_network:
        ipv4_address: 192.168.32.6

  # Packaging Enclave Services
  rfid_database:
    image: rfidapp/rfid-app-database
    container_name: rfid_database
    networks:
      packaging_network:
        ipv4_address: 192.168.33.3

  inventory_db:
    image: mysql/mysql-server:8.0
    container_name: inventory_db
    environment:
      MYSQL_ROOT_PASSWORD: inventory_pass
    networks:
      packaging_network:
        ipv4_address: 192.168.33.4

  inventory_client:
    image: ubuntu:latest
    container_name: inventory_client
    stdin_open: true
    tty: true
    depends_on:
      - inventory_db
    networks:
      packaging_network:
        ipv4_address: 192.168.33.5

  barcode_scanner:
    container_name: barcode_scanner
    build:
      context: ./barcode_scanner
      dockerfile: DockerFile
    ports:
      - "5001:5001"
    restart: always
    networks:
      packaging_network:
        ipv4_address: 192.168.33.6

  # Level 3 Site Operations Services
  ftp_server:
    image: delfer/alpine-ftp-server:latest
    container_name: ftp_server
    environment:
      USERS: "frp_user|alpine_fun_password123!"
    networks:
      site_operations_network:
        ipv4_address: 192.168.39.2
    entrypoint: ["/bin/sh", "-c", "sleep infinity"]

  # This database holds the data collected from the industrial operations and is then moved to the Historian DB in the Enterprise Network
  historian-db:
    image: influxdb:latest
    container_name: historian-db
    environment:
      - INFLUXDB_DB=historian
      - INFLUXDB_USER=admin
      - INFLUXDB_PASSWORD=securepass
    volumes:
        - historian_data:/var/lib/influxdb
    networks:
      site_operations_network:
        ipv4_address: 192.168.39.3
 
  historian-client:
      image: ubuntu:latest
      stdin_open: true
      tty: true
      container_name: historian-client
      depends_on:
        - historian-db
      networks:
        site_operations_network:
          ipv4_address: 192.168.39.4
  
  historian-server:
    build:
      context: ./site_operations
      dockerfile: DockerFile
    container_name: historian-server
    networks:
      site_operations_network:
        ipv4_address: 192.168.39.5
    depends_on:
      - historian-db
    ports:
      - "8001:5000"

  vds:
    image: dorowu/ubuntu-desktop-lxde-vnc  # Prebuilt lightweight Ubuntu Desktop that has 4 virtual desktops
    container_name: vds
    restart: unless-stopped
    ports:
      - "5901:5901"  # VNC Access
      - "8082:80"    # Web-based noVNC Access
    environment:
      - VNC_PASSWORD=securepassword
    networks:
      site_operations_network:
        ipv4_address: 192.168.39.6

networks:
  industrial_network:
    external: true
  assembly_network:
    external: true
  utilities_network:
    external: true
  packaging_network:
    external: true
  site_operations_network:
    external: true
  
volumes:
  openplc_data:
  scada_databases:
  logs:
  historian_data:
