services:
  historian-db:
    image: influxdb:latest
    container_name: historian-db
    restart: always
    environment:
      - INFLUXDB_DB=historian
      - INFLUXDB_USER=admin
      - INFLUXDB_PASSWORD=securepass
    volumes:
      - historian_data:/var/lib/influxdb
    networks:
      enterprise_network:
        ipv4_address: 192.168.10.2

  historian-client:
    image: ubuntu:latest
    container_name: historian-client
    depends_on:
      - historian-db
    networks:
      enterprise_network:
        ipv4_address: 192.168.10.3

  web-app:
    image: nginx:latest
    container_name: web-app
    volumes:
      - ./html:/usr/share/nginx/html:ro
    ports:
      - "8081:80"
    networks:
      enterprise_network:
        ipv4_address: 192.168.10.4

  frr_router:
    image: frrouting/frr:latest
    container_name: frr_router
    restart: always

  client_1:
    image: alpine:latest
    container_name: client_1
    networks:
      enterprise_network:
        ipv4_address: 192.168.10.5
#networks:
#  enterprise_network:
#    external: true

volumes:
  historian_data:
