services:
  web-app:
    image: nginx:latest
    container_name: web-app
    volumes:
      - ./html:/usr/share/nginx/html:ro
    ports:
      - "8081:80"
    networks:
      enterprise_network:
        ipv4_address: 192.168.10.2

  web-app-db:
     image: mysql:8.0
     restart: unless-stopped
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: web-app-db
       MYSQL_USER: webuser
       MYSQL_PASSWORD: db
     volumes:
       - webapp_db_data:/var/lib/mysql
     networks:
       enterprise_network:
         ipv4_address: 192.168.10.3
     ports:
       - "3308:3306"
  client_1:
    image: alpine:latest
    stdin_open: true
    tty: true
    container_name: client_1
    networks:
      enterprise_network:
        ipv4_address: 192.168.10.4
        
networks:
  enterprise_network:
    external: true

volumes:
  webapp_db_data:
