# .github/workflows/docker-network-ci.yml
name: CI – Validate Industrial Network Docker Compose

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-network:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Buildx (for builds)
        uses: docker/setup-buildx-action@v2

      - name: Validate Compose file
        run: docker compose -f docker-compose.yml config --quiet

      - name: Build all services
        run: docker compose -f docker-compose.yml build --parallel

      - name: Bring the network up
        run: docker compose -f docker-compose.yml up -d

      - name: Smoke-test containers
        run: |
          docker compose -f docker-compose.yml ps
          if docker compose -f docker-compose.yml ps --quiet \
             | xargs docker inspect --format '{{.State.Status}}' \
             | grep -E 'exited|dead'; then
            echo "::error ::One or more containers failed to start or died."
            exit 1
          fi

      - name: Tear down (always)
        if: always()
        run: docker compose -f docker-compose.yml down --remove-orphans
