name: CI - Validate Industrial Network Docker Compose

# Only allow the minimum GITHUB_TOKEN permissions
permissions:
  contents: read

# Trigger on pushes and PRs against main
on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  test-network:
    runs-on: ubuntu-latest

    # run all `run:` commands from the "network" folder
    defaults:
      run:
        working-directory: network

    steps:
      # 1) Checkout your code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Set up Docker Buildx (optional, but recommended for faster builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3) Validate your compose file syntax
      - name: Validate docker-compose.yml
        run: docker compose config --quiet

      # 4) Build all services in parallel
      - name: Build Docker services
        run: docker compose build --parallel

      # 5) Bring the network up in detached mode
      - name: Start the network
        run: docker compose up -d

      # 6) Smoke-test: fail if any container stopped or died immediately
      - name: Verify containers are healthy
        run: |
          echo "Container statuses:"
          docker compose ps
          # list container IDs that are not running
          FAILED=$(docker compose ps --quiet | xargs docker inspect --format '{{.State.Status}} {{.Id}}' \
            | awk '$1 != "running" { print $2 }')
          if [ -n "$FAILED" ]; then
            echo "::error ::Containers failed to start or died: $FAILED"
            exit 1
          fi

      # 7) Tear down the network (always)
      - name: Tear down
        if: always()
        run: docker compose down --remove-orphans
